---
# Установка и конфигурирование Zabbix Agent
- hosts: kvm-gpu-nodes
    become: true
    remote_user: lnxcfg

  tasks:
    - name: Установка Zabbix Agent
      yum: name="http://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-agent-4.4.9-1.el8.x86_64.rpm"
    - name: Смена IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: 'Server=192.168.10.10'
        backup: yes
    #- name: Zmiana Portu
    #  replace:
    #    path: /etc/zabbix/zabbix_agentd.conf
    #    regexp: '# ListenPort=10050'
    #    replace: 'ListenPort=10051'
    #    backup: yes
    - name: Изменение StartAgents с 3 на 5
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '# StartAgents=3'
        replace: 'StartAgents=5'
        backup: yes
    #- name: Zarejestruj hostname
    #  command: hostname
    #  register: nazwa
    #- name: Dodanie hostname
    #  replace:
    #    path: /etc/zabbix/zabbix_agentd.conf
    #    regexp: 'Hostname=Zabbix server'
    #    replace: 'Hostname={{ nazwa.stdout }}'
    - name: Запуск и добавление в автозагрузку zabbix-agent
      service: name=zabbix-agent state=started enabled=yes
    #- name: Добавление порта zabbix в firewalld
    #  firewalld:
    #        port: 10050/tcp
    #        permanent: yes
    #        state: enabled
    #- name: Перезапуск firewalld
    #  systemd:
    #        name: firewalld
    #        state: reloaded
